### ISSUE TITLE
number to braille 

### ISSUE THREAD

**Issue by kunal-iitkgp** [jpaugh/braille-converter#8]
any idea to how to get this done?

**Comment by jpaugh** [comment]
This is an old project, and I have not worked on it for a while; the Braille standard it targets (English Braille:American Edition) has since been deprecated by [Unified English Braille (UEB)][UEB], which is pretty different in some cases.

However, if you would like to update it, the program itself is fairly simple. The main complexity is in reading and understanding the standard for American Braille, and in implementing the rules in the correct order so that none of the gets missed. (E.g., if you convert the "be" in "between", then you loose the chance to convert the whole word "between" to its short form.)

This standard used to be available on http://www.brailleauthority.org, but as they are now advocating UEB, I can't find it anywhere.

[UEB]: http://www.brailleauthority.org/ueb.html

**Comment by jpaugh** [comment]
Oh, and if you do decide to work on this, let me know; I'll still accept pull requests although I'm not actively working on it
